version: 0.2
run-as: root
env:
  variables:
    OPENSEARCH_HOST: "api"


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 785975698029.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=785975698029.dkr.ecr.ap-south-1.amazonaws.com/ecs-package-repository
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs-package-repository:latest -f dockerfile .
      - echo "Updating fluent-bit.conf with the OpenSearch host"
      - sed -i 's|\${OPENSEARCH_HOST}|'$OPENSEARCH_HOST'|g' fluent-bit.conf
      - docker tag ecs-package-repository:latest 785975698029.dkr.ecr.ap-south-1.amazonaws.com/ecs-package-repository:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 785975698029.dkr.ecr.ap-south-1.amazonaws.com/ecs-package-repository:latest
artifacts:
    files: 
      - imagedefinitions.json
      - appspec.yml

